version: "3"
services:
    yabari_mysql:
        image: mysql:latest
        container_name: yabari_mysql
        hostname: yabari_mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: yabari
            TZ : Asia/Jakarta
        restart: unless-stopped
        volumes:
            - ./database:/var/lib/mysql
volumes:
    database:
